[build]
  command = "npm run build"   # Build command for React TypeScript
  publish = "dist"            # Change to "build" if using Create React App

[build.environment]
  NODE_VERSION = "18"         # Set your preferred Node.js version
  NPM_FLAGS = "--legacy-peer-deps"  # Avoid dependency conflicts

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
